export const MOCK_DATA = [
  {
    "name": "Micaela Victor",
    "designation": "Geba",
    "rating": 1,
    "reviewDescription": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    "reviewDate": "19.5.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 1 },
      { title: "Behavior", rating: 1 },
      { title: "Professionalism", rating: 1 },
      { title: "Proficiency", rating: 1 },
      { title: "Management", rating: 1 },
    ],
  },
  {
    "name": "Sophie Cobbledick",
    "designation": "Yadel",
    "rating": 1,
    "reviewDescription": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    "reviewDate": "20.5.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 1 },
      { title: "Behavior", rating: 5 },
      { title: "Professionalism", rating: 1 },
      { title: "Proficiency", rating: 1 },
      { title: "Management", rating: 1 },
    ],
  },
  {
    "name": "Quinlan Ivakhno",
    "designation": "Zoombeat",
    "rating": 1,
    "reviewDescription": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "reviewDate": "7.3.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 5 },
      { title: "Professionalism", rating: 5 },
      { title: "Proficiency", rating: 5 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Allianora Deas",
    "designation": "Trupe",
    "rating": 1,
    "reviewDescription": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    "reviewDate": "4.2.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 4 },
      { title: "Proficiency", rating: 3 },
      { title: "Management", rating: 1 },
    ],
  },
  {
    "name": "Hill O'Suaird",
    "designation": "Innojam",
    "rating": 4,
    "reviewDescription": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    "reviewDate": "31.10.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 1 },
      { title: "Behavior", rating: 1 },
      { title: "Professionalism", rating: 1 },
      { title: "Proficiency", rating: 1 },
      { title: "Management", rating: 1 },
    ],
  },
  {
    "name": "Linnea Laugherane",
    "designation": "Browseblab",
    "rating": 5,
    "reviewDescription": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    "reviewDate": "4.12.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 4 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 4 },
      { title: "Proficiency", rating: 4 },
      { title: "Management", rating: 5 },
    ],
  },
  {
    "name": "Maria Webbe",
    "designation": "Topiclounge",
    "rating": 3,
    "reviewDescription": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    "reviewDate": "5.1.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 3 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 3 },
      { title: "Management", rating: 3 },
    ],
  },
  {
    "name": "Rabi Rawlcliffe",
    "designation": "Kwimbee",
    "rating": 2,
    "reviewDescription": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    "reviewDate": "27.8.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 1 },
      { title: "Behavior", rating: 1 },
      { title: "Professionalism", rating: 1 },
      { title: "Proficiency", rating: 1 },
      { title: "Management", rating: 1 },
    ],
  },
  {
    "name": "Kristopher Pettis",
    "designation": "Minyx",
    "rating": 5,
    "reviewDescription": "Fusce consequat. Nulla nisl. Nunc nisl.",
    "reviewDate": "20.5.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 2 },
      { title: "Behavior", rating: 2 },
      { title: "Professionalism", rating: 2 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 2 },
    ],
  },
  {
    "name": "Carmine Brazener",
    "designation": "Skiptube",
    "rating": 4,
    "reviewDescription": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    "reviewDate": "22.12.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 3 },
      { title: "Behavior", rating: 3 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 3 },
      { title: "Management", rating: 3 },
    ],
  },
  {
    "name": "Annamarie Giovannacci",
    "designation": "Quinu",
    "rating": 2,
    "reviewDescription": "In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    "reviewDate": "23.10.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 2 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 2 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Letizia Grcic",
    "designation": "Kanoodle",
    "rating": 4,
    "reviewDescription": "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    "reviewDate": "5.7.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Ofella Faulds",
    "designation": "Mycat",
    "rating": 3,
    "reviewDescription": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    "reviewDate": "26.7.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Levi Balden",
    "designation": "Demivee",
    "rating": 3,
    "reviewDescription": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    "reviewDate": "31.1.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Nolan Standon",
    "designation": "BlogXS",
    "rating": 1,
    "reviewDescription": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.",
    "reviewDate": "20.2.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Chaim Decourcy",
    "designation": "Linkbridge",
    "rating": 5,
    "reviewDescription": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    "reviewDate": "23.7.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Jacinthe Hugin",
    "designation": "Divape",
    "rating": 1,
    "reviewDescription": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    "reviewDate": "14.6.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Cece Hains",
    "designation": "Edgepulse",
    "rating": 5,
    "reviewDescription": "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    "reviewDate": "27.6.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Talbert Liptrod",
    "designation": "Chatterbridge",
    "rating": 3,
    "reviewDescription": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    "reviewDate": "20.10.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Merci Eyckelberg",
    "designation": "Blogpad",
    "rating": 3,
    "reviewDescription": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    "reviewDate": "11.12.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Mela Sanbrooke",
    "designation": "Yabox",
    "rating": 4,
    "reviewDescription": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    "reviewDate": "30.5.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Graham Ortiga",
    "designation": "Zoonoodle",
    "rating": 4,
    "reviewDescription": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "reviewDate": "25.11.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Ricki Hayball",
    "designation": "LiveZ",
    "rating": 4,
    "reviewDescription": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    "reviewDate": "15.1.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Lennie Blackah",
    "designation": "Mita",
    "rating": 1,
    "reviewDescription": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    "reviewDate": "25.12.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Zulema Benzi",
    "designation": "Riffwire",
    "rating": 1,
    "reviewDescription": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    "reviewDate": "7.1.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Sanford Sherman",
    "designation": "Flashset",
    "rating": 4,
    "reviewDescription": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    "reviewDate": "5.8.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Dulci Nudde",
    "designation": "Tavu",
    "rating": 4,
    "reviewDescription": "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    "reviewDate": "3.12.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Dylan Groomebridge",
    "designation": "Twiyo",
    "rating": 5,
    "reviewDescription": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    "reviewDate": "20.6.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Salim Lohoar",
    "designation": "Thoughtsphere",
    "rating": 3,
    "reviewDescription": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    "reviewDate": "13.6.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Ardra Gourley",
    "designation": "Wikibox",
    "rating": 3,
    "reviewDescription": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    "reviewDate": "19.3.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Dorothy Capon",
    "designation": "Reallinks",
    "rating": 2,
    "reviewDescription": "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    "reviewDate": "7.7.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Quintana Giddons",
    "designation": "Quinu",
    "rating": 3,
    "reviewDescription": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    "reviewDate": "2.11.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Wini Bevington",
    "designation": "Riffwire",
    "rating": 4,
    "reviewDescription": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    "reviewDate": "2.2.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Teodora Alywin",
    "designation": "Divape",
    "rating": 4,
    "reviewDescription": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    "reviewDate": "14.3.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Arnaldo Oxbury",
    "designation": "Trunyx",
    "rating": 1,
    "reviewDescription": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    "reviewDate": "28.2.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Rhianon Sporton",
    "designation": "Npath",
    "rating": 1,
    "reviewDescription": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "reviewDate": "19.12.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Giff Clearie",
    "designation": "Podcat",
    "rating": 5,
    "reviewDescription": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    "reviewDate": "3.2.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Eadie Cases",
    "designation": "Photolist",
    "rating": 4,
    "reviewDescription": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    "reviewDate": "18.11.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Marleah Matskevich",
    "designation": "Zoozzy",
    "rating": 4,
    "reviewDescription": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    "reviewDate": "16.1.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Arlette Schruyer",
    "designation": "Youspan",
    "rating": 3,
    "reviewDescription": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    "reviewDate": "4.5.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Holly-anne Vasechkin",
    "designation": "Buzzbean",
    "rating": 1,
    "reviewDescription": "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    "reviewDate": "18.4.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Krystal Livermore",
    "designation": "Babblestorm",
    "rating": 5,
    "reviewDescription": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    "reviewDate": "4.9.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Robert Geeritz",
    "designation": "Skinte",
    "rating": 3,
    "reviewDescription": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    "reviewDate": "4.2.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Yettie Cornell",
    "designation": "Thoughtbridge",
    "rating": 3,
    "reviewDescription": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    "reviewDate": "7.3.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Lauritz O'Hannigan",
    "designation": "Edgepulse",
    "rating": 4,
    "reviewDescription": "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    "reviewDate": "8.5.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Jarad Piscopiello",
    "designation": "Twinder",
    "rating": 1,
    "reviewDescription": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    "reviewDate": "8.10.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Shelbi Petchell",
    "designation": "Blogtags",
    "rating": 5,
    "reviewDescription": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    "reviewDate": "28.6.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Lorita Dilkes",
    "designation": "Zooveo",
    "rating": 4,
    "reviewDescription": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    "reviewDate": "2.9.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Jewel Alkins",
    "designation": "Browsedrive",
    "rating": 1,
    "reviewDescription": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "reviewDate": "19.5.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Zolly Dyment",
    "designation": "Jayo",
    "rating": 2,
    "reviewDescription": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    "reviewDate": "10.1.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Garik Lightoller",
    "designation": "Gigashots",
    "rating": 5,
    "reviewDescription": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    "reviewDate": "29.11.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Gabie Russ",
    "designation": "Dynabox",
    "rating": 1,
    "reviewDescription": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    "reviewDate": "17.7.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Dorita Pointin",
    "designation": "Einti",
    "rating": 5,
    "reviewDescription": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    "reviewDate": "19.4.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Tabatha Habble",
    "designation": "Demivee",
    "rating": 3,
    "reviewDescription": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    "reviewDate": "7.6.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Liesa Blackborn",
    "designation": "Blognation",
    "rating": 3,
    "reviewDescription": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    "reviewDate": "3.1.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Farley Ackrill",
    "designation": "Linkbuzz",
    "rating": 2,
    "reviewDescription": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    "reviewDate": "25.4.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Coretta Tweede",
    "designation": "Skiptube",
    "rating": 1,
    "reviewDescription": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "reviewDate": "21.8.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Welby Grennan",
    "designation": "Voonte",
    "rating": 1,
    "reviewDescription": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    "reviewDate": "17.4.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Wyndham Bendel",
    "designation": "Ooba",
    "rating": 3,
    "reviewDescription": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "reviewDate": "1.1.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Emelen Hamlington",
    "designation": "Miboo",
    "rating": 1,
    "reviewDescription": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    "reviewDate": "29.5.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Mendel Duckworth",
    "designation": "Oyoyo",
    "rating": 2,
    "reviewDescription": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "reviewDate": "31.1.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Rani Noden",
    "designation": "Voolia",
    "rating": 2,
    "reviewDescription": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    "reviewDate": "3.3.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Kellina Hammand",
    "designation": "Buzzshare",
    "rating": 4,
    "reviewDescription": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    "reviewDate": "20.7.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Aldus Petruszka",
    "designation": "Skivee",
    "rating": 5,
    "reviewDescription": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    "reviewDate": "2.3.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Skipp Benito",
    "designation": "Miboo",
    "rating": 3,
    "reviewDescription": "Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    "reviewDate": "9.2.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Phyllis Lamey",
    "designation": "Brightbean",
    "rating": 1,
    "reviewDescription": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    "reviewDate": "28.5.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Gill Palin",
    "designation": "Shuffledrive",
    "rating": 2,
    "reviewDescription": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    "reviewDate": "1.1.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Dudley Bambury",
    "designation": "Quimba",
    "rating": 5,
    "reviewDescription": "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "reviewDate": "8.5.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Ibbie Checci",
    "designation": "Shuffletag",
    "rating": 1,
    "reviewDescription": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "reviewDate": "18.2.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Audrey Yesipov",
    "designation": "Kaymbo",
    "rating": 2,
    "reviewDescription": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    "reviewDate": "19.7.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Mamie Threadgall",
    "designation": "Tagchat",
    "rating": 3,
    "reviewDescription": "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    "reviewDate": "10.2.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Farrel Adame",
    "designation": "Reallinks",
    "rating": 3,
    "reviewDescription": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    "reviewDate": "14.4.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Stefanie Outright",
    "designation": "Pixoboo",
    "rating": 4,
    "reviewDescription": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "reviewDate": "11.5.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Mitch Pawlowicz",
    "designation": "Mynte",
    "rating": 2,
    "reviewDescription": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    "reviewDate": "1.9.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Gordan Raun",
    "designation": "Kaymbo",
    "rating": 1,
    "reviewDescription": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    "reviewDate": "20.2.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Catherin Fernant",
    "designation": "Meevee",
    "rating": 4,
    "reviewDescription": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    "reviewDate": "25.4.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Beryle Jacklings",
    "designation": "Rhyloo",
    "rating": 4,
    "reviewDescription": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "reviewDate": "6.12.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Byran Mackerness",
    "designation": "Ooba",
    "rating": 1,
    "reviewDescription": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "reviewDate": "9.11.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Dallon Doig",
    "designation": "Yabox",
    "rating": 4,
    "reviewDescription": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "reviewDate": "13.6.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Trina Windle",
    "designation": "Edgetag",
    "rating": 1,
    "reviewDescription": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    "reviewDate": "10.10.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Walt Gethings",
    "designation": "Centimia",
    "rating": 1,
    "reviewDescription": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    "reviewDate": "28.6.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Reece Jesty",
    "designation": "Dabfeed",
    "rating": 2,
    "reviewDescription": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    "reviewDate": "13.12.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Juana McElvogue",
    "designation": "Blognation",
    "rating": 3,
    "reviewDescription": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    "reviewDate": "18.4.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Caron Clist",
    "designation": "Livetube",
    "rating": 5,
    "reviewDescription": "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    "reviewDate": "30.1.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Stanislaus Redsall",
    "designation": "Wordpedia",
    "rating": 5,
    "reviewDescription": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    "reviewDate": "1.7.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Piggy Batrop",
    "designation": "Meevee",
    "rating": 1,
    "reviewDescription": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    "reviewDate": "24.11.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Elliot Trimnell",
    "designation": "Topicware",
    "rating": 2,
    "reviewDescription": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    "reviewDate": "8.12.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Ainsley Mount",
    "designation": "Zoonoodle",
    "rating": 2,
    "reviewDescription": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    "reviewDate": "29.4.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Staford McCarty",
    "designation": "Kwinu",
    "rating": 5,
    "reviewDescription": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "reviewDate": "22.1.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Etta Dumbrill",
    "designation": "Skajo",
    "rating": 3,
    "reviewDescription": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "reviewDate": "13.8.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Glyn Kaemena",
    "designation": "Edgeblab",
    "rating": 3,
    "reviewDescription": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    "reviewDate": "25.5.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Corbett Smythin",
    "designation": "Wordify",
    "rating": 3,
    "reviewDescription": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "reviewDate": "16.5.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Edy Harly",
    "designation": "Podcat",
    "rating": 3,
    "reviewDescription": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    "reviewDate": "15.12.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Marvin Tumilson",
    "designation": "Dynava",
    "rating": 1,
    "reviewDescription": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    "reviewDate": "16.10.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Angie Wassell",
    "designation": "Kamba",
    "rating": 4,
    "reviewDescription": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "reviewDate": "21.7.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Marvin Klauer",
    "designation": "Brainbox",
    "rating": 3,
    "reviewDescription": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    "reviewDate": "16.12.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Damian Karlolak",
    "designation": "Layo",
    "rating": 1,
    "reviewDescription": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    "reviewDate": "5.12.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Padgett Cabrales",
    "designation": "Vinder",
    "rating": 5,
    "reviewDescription": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    "reviewDate": "19.10.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Augustina Hardcastle",
    "designation": "Livetube",
    "rating": 2,
    "reviewDescription": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    "reviewDate": "25.9.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Sheridan Paish",
    "designation": "Realbridge",
    "rating": 3,
    "reviewDescription": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    "reviewDate": "4.7.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Sollie Keirle",
    "designation": "Yakijo",
    "rating": 5,
    "reviewDescription": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    "reviewDate": "18.4.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Lisabeth Kunert",
    "designation": "Babbleopia",
    "rating": 5,
    "reviewDescription": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    "reviewDate": "9.10.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Rick Longmate",
    "designation": "Feednation",
    "rating": 3,
    "reviewDescription": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    "reviewDate": "27.6.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Connor Thebe",
    "designation": "Photospace",
    "rating": 5,
    "reviewDescription": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    "reviewDate": "1.4.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Merle Steart",
    "designation": "Voomm",
    "rating": 3,
    "reviewDescription": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    "reviewDate": "16.9.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Sarena Fearneley",
    "designation": "Talane",
    "rating": 4,
    "reviewDescription": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    "reviewDate": "7.6.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Tressa Gatling",
    "designation": "Zooveo",
    "rating": 4,
    "reviewDescription": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    "reviewDate": "28.9.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Billye Caban",
    "designation": "Katz",
    "rating": 3,
    "reviewDescription": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    "reviewDate": "6.4.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Trumaine Grigoryov",
    "designation": "Kayveo",
    "rating": 4,
    "reviewDescription": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    "reviewDate": "7.11.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Berri Maiklem",
    "designation": "Thoughtbridge",
    "rating": 4,
    "reviewDescription": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    "reviewDate": "24.6.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Mariette Sampson",
    "designation": "Tambee",
    "rating": 1,
    "reviewDescription": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    "reviewDate": "1.4.2023",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Fitzgerald Lorence",
    "designation": "Kwimbee",
    "rating": 4,
    "reviewDescription": "Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    "reviewDate": "14.11.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Neill Gregoratti",
    "designation": "Centizu",
    "rating": 5,
    "reviewDescription": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "reviewDate": "10.11.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Polly Messent",
    "designation": "Pixope",
    "rating": 5,
    "reviewDescription": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    "reviewDate": "26.6.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Sydney Chate",
    "designation": "Dabjam",
    "rating": 4,
    "reviewDescription": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    "reviewDate": "8.8.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Mikaela MacClay",
    "designation": "Kwimbee",
    "rating": 5,
    "reviewDescription": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    "reviewDate": "15.8.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Seth Danielli",
    "designation": "Skyba",
    "rating": 4,
    "reviewDescription": "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    "reviewDate": "27.11.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Sarah Josland",
    "designation": "Realbuzz",
    "rating": 1,
    "reviewDescription": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "reviewDate": "1.10.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Elsy Whiscard",
    "designation": "Yakitri",
    "rating": 5,
    "reviewDescription": "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    "reviewDate": "23.11.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  },
  {
    "name": "Paola Nowland",
    "designation": "Voonix",
    "rating": 3,
    "reviewDescription": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    "reviewDate": "11.6.2022",
    "reviewDetails": "See More Details",
    detaisReating: [
      { title: "Responsibility", rating: 5 },
      { title: "Behavior", rating: 4 },
      { title: "Professionalism", rating: 3 },
      { title: "Proficiency", rating: 2 },
      { title: "Management", rating: 4 },
    ],
  }
].map(data => {
  const { detaisReating } = data;
  const ratingSum = detaisReating.reduce((sum, item) => sum + item.rating, 0);
  const averageRating = ratingSum / detaisReating.length;

  return {
    ...data,
    rating: averageRating,
    id: Math.random().toString(36).substr(2, 9)
  };
})
// add a property with name , date and rating